services:
  - type: web
    name: regresion-frontend
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist